### ISSUE TITLE
Convert srt subtitles to vtt format

### ISSUE THREAD

**Issue by kollivier** [learningequality/pressurecooker#19]
Ciencia NASA has video subtitles in srt format, but Kolibri only supports vtt format. Studio and ricecooker should have a way to convert these subtitles into vtt format. An easy solution would probably be to just use this library:

https://pypi.org/project/webvtt-py/

**Comment by ivanistheone** [comment]
Implemented in https://github.com/learningequality/pressurecooker/pull/21
