### ISSUE TITLE
Extract metadata from PDFs

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/pressurecooker#24]
It would be nice to extract author / title from PDF metadata when uploading files to Studio --- these could pre-populate the metadate editing wizard. Here is an article with info about various metadata in PDFs: https://pspdfkit.com/blog/2018/whats-hiding-in-your-pdf/
via https://news.ycombinator.com/item?id=18381515

Also,  auto-generated thumbnail from the PDF would be very useful --- currently many of the documents don't have a thumbnail.

**Comment by rtibbles** [comment]
No longer using pressurecooker on Studio, so this is moot.
