### ISSUE TITLE
srt2vtt dependecy webvtt-py is Py3.4+ only

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/pressurecooker#25]
See https://pypi.org/project/webvtt-py/

This shouldn't be a problem on studio if we don't import `pressurecooker.converters`, but we'll have to address this before we introduce subs conversion on Studio. 

Desired resolution is for this issue to go away on it's own once we update Studio to Py3; otherwise we'll have to find another library to convert subs.

**Comment by bjester** [comment]
I'm hoping to integrate https://github.com/pbs/pycaption but there's an issue with `beautifulsoup`. They require `beautifulsoup4>=4.2.1,<4.5.0` and `pressurecooker` requires `beautifulsoup4>=4.6.3`. 

I was able to fix the tests that should help [this PR](https://github.com/pbs/pycaption/pull/185) get merged, so it has simultaneous python 2 and 3 support in a single release.

**Comment by bjester** [comment]
Woohoo! They've merged https://github.com/pbs/pycaption/pull/185 and I created https://github.com/pbs/pycaption/pull/187 so hopefully they make a new release out of all that. Perhaps it'll be pycaption 2.0
