### ISSUE TITLE
le-pycaption dependency: There are other active upstreams

### ISSUE THREAD

**Issue by benjaoming** [learningequality/pressurecooker#50]
pycaption is clearly abandoned, but there are people working with other forks, so perhaps it'd be good to join forces?

https://github.com/pbs/pycaption/issues/200

They removed the `future` dependency so this would not have been necessary CC: @ivanistheone  https://github.com/learningequality/pycaption/pull/8

**Comment by ivanistheone** [comment]
`le-pycaption` py27 branch was updated in https://github.com/learningequality/pycaption/pull/11 so it's back in good shape
